name: deepseek-env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=23.0
  - pytorch>=2.0.0
  - pytorch-cuda=11.8
  - transformers>=4.36.0
  - accelerate>=0.24.0
  - bitsandbytes>=0.41.1  # For 8-bit quantization
  - pip:
    - sentencepiece
    - protobuf
    - safetensors>=0.3.1