name: deepseek-env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=23.0
  # PyTorch with CUDA 11.8 support (compatible versions)
  - pytorch>=2.1.0,<2.5.0
  - torchvision>=0.16.0,<0.20.0
  - torchaudio>=2.1.0,<2.5.0
  - pytorch-cuda=11.8
  # Core ML libraries
  - numpy>=1.24.0,<2.0.0
  - pip:
    # HuggingFace ecosystem (compatible versions)
    - transformers>=4.40.0,<4.50.0
    - accelerate>=0.25.0,<1.0.0
    - tokenizers>=0.15.0
    # Quantization (compatible version)
    - bitsandbytes>=0.41.0,<0.44.0
    # Model and data handling
    - safetensors>=0.4.0,<0.5.0
    - sentencepiece>=0.1.99
    - protobuf>=3.20.0,<5.0.0
    # Utilities
    - tqdm>=4.64.0
    - requests>=2.28.0
    # Development tools
    - black>=22.0.0
    - pytest>=7.0.0