name: deepseek-env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=23.0
  - pytorch>=2.7.1
  - pytorch-cuda=11.8
  - transformers>=4.53.1
  - accelerate>=1.8.1
  - bitsandbytes>=0.46.1  # For 8-bit quantization
  - pip:
    - sentencepiece
    - protobuf
    - safetensors>=0.4.4
    - numpy>=1.24.0
    - tqdm
    - black
    - pytest